version: '2'
services:
    translator:
        image: node
        ports:
            - 8687:8687
        volumes:
             - ./translator:/opt/translator
             - ./run.sh:/opt/run.sh
             - ./readme.md:/opt/readme.md
        command: ["sleep","infinity"]